baseURL = "https://maxwellcleaningservice.com"
title = "Maxwell Cleaning Services"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = false

canonifyURLs = true

enableRobotsTXT = true # generate robots.txt

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "Maxwell Cleaning Service"
title404 = "Page Not Found"

[params]
description = "Maxwell Cleaning Services provides superior cleaning solutions including carpet cleaning, window cleaning, and janitorial services. Servicing Klamath Falls and surrounding areas."
pagetitle = "Maxwell Cleaning Services"
noindex_kinds = [
  "taxonomy",
  "taxonomyTerm"
]

disableKinds = ["taxonomy", "taxonomyTerm"]

[params.assets]
favicon = "favicon.ico"
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Maxwell Cleaning Services. All Rights Reserved."
startYear = "2016"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "Jan 02, 2006"
listDateFormat = "Jan 02, 2006"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Carpet Cleaning"
weight = 1
identifier = "Carpet Cleaning"
url = "carpet-cleaning"

[[menu.main]]
name = "Window Cleaning"
weight = 2
identifier = "Window Cleaning"
url = "window-cleaning"

[[menu.main]]
name = "Janitorial"
weight = 3
identifier = "Janitorial"
url = "janitorial"

[[menu.main]]
name = "Contact"
weight = 4
identifier = "Contact"
class = "contact"
url = "#"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
